<?php

declare(strict_types=1);

namespace Toporia\Framework\Console\Commands;

use Toporia\Framework\Console\Command;
use Toporia\Framework\Foundation\Application;

/**
 * Class ConfigCacheCommand
 *
 * Compile all configuration files into a single cached file for faster loading.
 *
 * @author      Phungtruong7820 <minhphung485@gmail.com>
 * @copyright   Copyright (c) 2025 Toporia Framework
 * @license     MIT
 * @version     1.0.0
 * @package     toporia/framework
 * @subpackage  Console\Commands
 * @since       2025-01-10
 *
 * @link        https://github.com/Minhphung7820/toporia
 */
final class ConfigCacheCommand extends Command
{
    protected string $signature = 'config:cache';
    protected string $description = 'Cache configuration files for faster performance';

    public function __construct(
        private readonly Application $app
    ) {}

    public function handle(): int
    {
        $startTime = microtime(true);

        $this->printHeader();

        $configPath = $this->app->path('config');
        $cachePath = $this->getCachePath();

        // Ensure cache directory exists
        if (!is_dir(dirname($cachePath))) {
            mkdir(dirname($cachePath), 0755, true);
        }

        // Clear old cache
        if (file_exists($cachePath)) {
            @unlink($cachePath);
            $this->info('  Cleared old cache');
        }

        // Load all config files
        $this->info('  Compiling configuration files...');
        $config = $this->loadAllConfigs($configPath);

        // Write cache file
        $success = $this->writeCache($cachePath, $config);

        if (!$success) {
            $this->error('  ✗  Failed to cache configuration');
            return 1;
        }

        // Print summary
        $duration = round((microtime(true) - $startTime) * 1000, 2);
        $count = count($config);
        $this->printSummary($count, $cachePath, $duration);

        return 0;
    }

    /**
     * Load all configuration files from directory.
     *
     * @param string $configPath
     * @return array<string, mixed>
     */
    private function loadAllConfigs(string $configPath): array
    {
        $config = [];

        if (!is_dir($configPath)) {
            return $config;
        }

        $files = glob($configPath . '/*.php');

        foreach ($files as $file) {
            $name = basename($file, '.php');
            $config[$name] = require $file;
        }

        return $config;
    }

    /**
     * Write compiled config to cache file.
     *
     * @param string $cachePath
     * @param array<string, mixed> $config
     * @return bool
     */
    private function writeCache(string $cachePath, array $config): bool
    {
        $content = "<?php\n\n";
        $content .= "declare(strict_types=1);\n\n";
        $content .= "/**\n";
        $content .= " * Compiled Configuration Cache\n";
        $content .= " *\n";
        $content .= " * This file is auto-generated by 'php console config:cache'.\n";
        $content .= " * Do not edit this file directly.\n";
        $content .= " *\n";
        $content .= " * Generated: " . now()->toDateTimeString() . "\n";
        $content .= " */\n\n";
        $content .= "return " . var_export($config, true) . ";\n";

        return file_put_contents($cachePath, $content) !== false;
    }

    /**
     * Get cache file path.
     *
     * @return string
     */
    private function getCachePath(): string
    {
        return $this->app->path('storage/framework/config.php');
    }

    private function printHeader(): void
    {
        $this->info('');
        $this->info('┌─────────────────────────────────────────────────────────────────┐');
        $this->info('│                  CONFIG CACHING                                   │');
        $this->info('└─────────────────────────────────────────────────────────────────┘');
        $this->info('');
    }

    private function printSummary(int $count, string $cachePath, float $duration): void
    {
        $this->info('');
        $this->info('┌─────────────────────────────────────────────────────────────────┐');
        $this->success('  ✓  Cached: ' . $count . ' configuration files');
        $this->line('     Path: ' . $cachePath);
        $this->line('     Duration: ' . $duration . 'ms');
        $this->info('└─────────────────────────────────────────────────────────────────┘');
        $this->info('');
        $this->success('  Configuration cached successfully! 🚀');
        $this->info('');
    }
}
